version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: devdb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
  kigurumi_backend:
    image: tregubovatonia/kigurumi-backend
    environment:
      PORT: 8000
      MONGO_URL: mongodb://devuser:qwerty123@mongodb:27017/devdb
    ports: 
      - 32456:32456
      - 8000:8000
    restart: always  
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
